receivers:
  filelog:
    include: [ /var/log/*.txt ]

exporters:
  awskinesis:
    queue_size: 1
    num_workers: 1
    flush_interval_seconds: 3
    max_bytes_per_batch: 4
    max_bytes_per_span: 5

    aws:
        region: ap-southeast-2
        stream_name: dev_cde_tstream
        role: arn:aws:kinesis:ap-southeast-2:180949727245:stream/dev_cde_tstream
        awskinesis_endpoint: kinesis.ap-southeast-2.amazonaws.com

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [filelog]
      processors: [batch]
      exporters: [awskinesis]